<a href="https://colab.research.google.com/github/akm-coder/ml_assignment/blob/main/pca_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/amsPredictionSheet1-201009-150447.csv")
df.head()

Attendance  MSE  HRS  ESE
0          70   10   17   42
1          92    7   20   39
2          67    3   18   32
3          82   16   13   50
4          80    9   10   44

In [ ]:
df.describe()

Attendance        MSE        HRS        ESE
count   73.000000  73.000000  73.000000  73.000000
mean    81.698630   9.780822  12.904110  46.630137
std      9.506847   3.047069   5.701278   6.617542
min     62.000000   3.000000   2.000000  32.000000
25%     75.000000   8.000000   8.000000  42.000000
50%     80.000000  10.000000  14.000000  47.000000
75%     90.000000  11.000000  18.000000  50.000000
max     98.000000  17.000000  22.000000  64.000000

In [ ]:
endog = df["ESE"].head()
exog = df[["MSE","Attendance", "HRS"]].head()
print(exog)

   MSE  Attendance  HRS
0   10          70   17
1    7          92   20
2    3          67   18
3   16          82   13
4    9          80   10


In [ ]:
X = exog.to_numpy()
Y = endog.to_numpy()
print(X)

[[10 70 17]
 [ 7 92 20]
 [ 3 67 18]
 [16 82 13]
 [ 9 80 10]]


In [ ]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [ ]:
M = mean(X.T, axis = 1)
print(M)

[ 9.  78.2 15.6]


In [ ]:
C = X-M
print(C)

[[  1.   -8.2   1.4]
 [ -2.   13.8   4.4]
 [ -6.  -11.2   2.4]
 [  7.    3.8  -2.6]
 [  0.    1.8  -5.6]]


In [ ]:
V = cov(C.T)
print(V)

[[ 22.5  14.5 -10. ]
 [ 14.5 100.2   0.6]
 [-10.    0.6  16.3]]


In [ ]:
values, vectors = eig(V)
print(values)
print(vectors)

[102.83421474  28.19086641   7.97491885]
[[-0.1792837  -0.75344094  0.63260107]
 [-0.98369925  0.14637427 -0.10445268]
 [ 0.01389759  0.64101586  0.7674018 ]]


In [ ]:
P = vectors.T.dot(C.T)
print(P.T)

[[  7.90650678  -1.05628772   2.56347554]
 [-13.15533283   6.34731651   0.66991886]
 [ 12.126488     4.4196919   -0.7839721 ]
 [ -5.02917677  -6.38450557   2.03604261]
 [ -1.84848518  -3.32621512  -4.48546492]]


In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalcomponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalcomponents, columns = ["principal Component 1"])

In [ ]:
import statsmodels.api as sm
exog1 = sm.add_constant(principalDf[["principal Component 1"]])
print(exog1)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


   const  principal Component 1
0    1.0              -7.906507
1    1.0              13.155333
2    1.0             -12.126488
3    1.0               5.029177
4    1.0               1.848485


In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
model = lr.fit(exog1, endog)

In [ ]:
lr.coef_

array([0.       , 0.3056601])

In [ ]:
lr.intercept_

41.4

In [ ]:
import math
def RSE(y_true, y_predicted):
  y_true = np.array(y_true)
  y_predicted = np.array(y_predicted)
  RSS = np.sum(np.square(y_true-y_predicted))
  rse = math.sqrt(RSS/(len(y_true)-2))
  return rse

In [ ]:
ypred = lr.predict(exog1)

In [ ]:
re = RSE(endog, ypred)
print(re)

6.752026356402884
